### ISSUE TITLE
Linker issues with SymbolicOperator and SymbolicOperatorUtils

### ISSUE THREAD

**Issue by HenryHelstad** [IntelLabs/Hybrid-Quantum-Classical-Library#9]
When compiling an example problems on the most current version of main; compilation will fail with linker errors similar to: 
`ld.lld: error: undefined symbol: hybrid::quantum::core::SymbolicOperator::addTerm(std::set<std::pair<int, char> …`
For symbols declared in SymbolicOperator.hpp and SymbolicOperatorUtils.hpp.  

When reverting to 0.4.0 it works with the same recommended compilation script (in the file) and build steps (from the README). 

My expectation is something small changed breaking the linker.

**Comment by atulkulk** [comment]
Thanks for reporting the issue! It has been fixed now.
